name: hl_des
description: A new flutter plugin project.
version: 2.0.2
homepage: https://github.com/hoanglm4/hl_des

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: hlsolutions.flutter_des.hl_des
        pluginClass: HlDesPlugin
      ios:
        pluginClass: HlDesPlugin
